services:
  app:
    image: authorization-service-app
    build: .
    container_name: authorization-service
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: always
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: PaymentApp
      POSTGRES_USER: lost
      POSTGRES_PASSWORD: 123
    restart: always
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true